version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./app/node_modules

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app